version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: shoppinglist-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8917aJf1996
      POSTGRES_DB: shoppinglist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: shoppinglist-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 8917aJf1996
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
